/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:a00008d4-f58b-4d06-b56c-a6b565ed8f8f",
    "aws_cognito_region": "eu-west-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "b2e568168ae34a2e8556a74280d63d69",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
